import type { AudioDef } from './types';

// Every sound the game can request. The placeholder names a procedural
// generator in @pvz/audio; a supplied asset with the same id replaces it.
export const audioDefs: AudioDef[] = [
  { id: 'music.menu', channel: 'music', placeholder: 'music-menu', loop: true, volume: 0.7 },
  { id: 'music.choose-seeds', channel: 'music', placeholder: 'music-choose', loop: true, volume: 0.7 },
  { id: 'music.day', channel: 'music', placeholder: 'music-day', loop: true, volume: 0.6 },
  { id: 'music.night', channel: 'music', placeholder: 'music-night', loop: true, volume: 0.6 },
  { id: 'music.minigame', channel: 'music', placeholder: 'music-minigame', loop: true, volume: 0.6 },
  { id: 'audio.win', channel: 'sfx', placeholder: 'jingle-win' },
  { id: 'audio.lose', channel: 'sfx', placeholder: 'jingle-lose' },
  { id: 'audio.plant', channel: 'sfx', placeholder: 'plant', maxInstances: 3 },
  { id: 'audio.throw', channel: 'sfx', placeholder: 'throw', maxInstances: 6, volume: 0.6 },
  { id: 'audio.splat', channel: 'sfx', placeholder: 'splat', maxInstances: 6, volume: 0.7 },
  { id: 'audio.plastic-hit', channel: 'sfx', placeholder: 'plastic-hit', maxInstances: 4, volume: 0.6 },
  { id: 'audio.points', channel: 'sfx', placeholder: 'points', maxInstances: 4 },
  { id: 'audio.chomp', channel: 'sfx', placeholder: 'chomp', maxInstances: 4, volume: 0.6 },
  { id: 'audio.gulp', channel: 'sfx', placeholder: 'gulp', maxInstances: 2 },
  { id: 'audio.groan', channel: 'sfx', placeholder: 'groan', maxInstances: 2, volume: 0.5 },
  { id: 'audio.limbs-pop', channel: 'sfx', placeholder: 'pop', maxInstances: 4 },
  { id: 'audio.zombie-fall', channel: 'sfx', placeholder: 'thud', maxInstances: 3, volume: 0.6 },
  { id: 'audio.lawnmower', channel: 'sfx', placeholder: 'lawnmower', maxInstances: 2 },
  { id: 'audio.awooga', channel: 'sfx', placeholder: 'awooga' },
  { id: 'audio.siren', channel: 'sfx', placeholder: 'siren' },
  { id: 'audio.final-wave', channel: 'sfx', placeholder: 'final-wave' },
  { id: 'audio.ready-set-plant', channel: 'sfx', placeholder: 'ready' },
  { id: 'audio.reward', channel: 'sfx', placeholder: 'reward' },
  { id: 'audio.puff', channel: 'sfx', placeholder: 'puff', maxInstances: 6, volume: 0.5 },
  { id: 'audio.fume', channel: 'sfx', placeholder: 'fume', maxInstances: 4, volume: 0.6 },
  { id: 'audio.frozen-hit', channel: 'sfx', placeholder: 'frozen-hit', maxInstances: 6, volume: 0.6 },
  { id: 'audio.metal-hit', channel: 'sfx', placeholder: 'metal-hit', maxInstances: 6, volume: 0.5 },
  { id: 'audio.paper-hit', channel: 'sfx', placeholder: 'paper-hit', maxInstances: 4, volume: 0.6 },
  { id: 'audio.explosion', channel: 'sfx', placeholder: 'explosion', maxInstances: 3 },
  { id: 'audio.potato-mine', channel: 'sfx', placeholder: 'potato-mine', maxInstances: 3 },
  { id: 'audio.doom', channel: 'sfx', placeholder: 'doom', maxInstances: 2 },
  { id: 'audio.frozen', channel: 'sfx', placeholder: 'frozen', maxInstances: 2 },
  { id: 'audio.chomper-bite', channel: 'sfx', placeholder: 'chomper-bite', maxInstances: 3 },
  { id: 'audio.grave-buster', channel: 'sfx', placeholder: 'grave-buster', maxInstances: 2 },
  { id: 'audio.hypno', channel: 'sfx', placeholder: 'hypno', maxInstances: 2 },
  { id: 'audio.vault', channel: 'sfx', placeholder: 'vault', maxInstances: 3, volume: 0.6 },
  { id: 'audio.rage', channel: 'sfx', placeholder: 'rage', maxInstances: 2 },
  { id: 'audio.dancer', channel: 'sfx', placeholder: 'dancer', maxInstances: 2 },
  { id: 'audio.dirt-rise', channel: 'sfx', placeholder: 'dirt-rise', maxInstances: 3, volume: 0.6 },
  { id: 'audio.bowling', channel: 'sfx', placeholder: 'bowling', maxInstances: 3, volume: 0.6 },
  { id: 'audio.bowling-impact', channel: 'sfx', placeholder: 'bowling-impact', maxInstances: 4 },
  { id: 'audio.whack', channel: 'sfx', placeholder: 'whack', maxInstances: 3 },
  { id: 'audio.shovel', channel: 'sfx', placeholder: 'shovel', maxInstances: 2 },
  { id: 'audio.tap', channel: 'ui', placeholder: 'tap', maxInstances: 2 },
  { id: 'audio.seed-lift', channel: 'ui', placeholder: 'seed-lift', maxInstances: 2 },
  { id: 'audio.buzzer', channel: 'ui', placeholder: 'buzzer', maxInstances: 1 },
  { id: 'audio.pause', channel: 'ui', placeholder: 'pause', maxInstances: 1 },
];
