import type {
  BowlSpec,
  ChomperSpec,
  ExplodeSpec,
  FreezeAllSpec,
  FumeSpec,
  MineSpec,
  PlantDef,
  ProducerSpec,
  ShooterSpec,
} from '@pvz/engine';

// PvZ 1 values (centisecond timings converted to seconds). See
// COMPATIBILITY.md for what is measured and what is still approximate.

const peaShot = {
  type: 'shooter',
  interval: 1.5,
  intervalJitter: 0.15,
  fireDelay: 0.35,
  initialDelay: 0,
  spawnOffset: { x: 45, y: 32 },
} as const;

const sunProduction: ProducerSpec = {
  type: 'producer',
  amount: 25,
  firstDelay: [3, 12.5],
  interval: [23.5, 25],
  glowLead: 1,
};

const sporeShot = {
  type: 'shooter',
  projectile: 'spore',
  interval: 1.5,
  intervalJitter: 0.15,
  fireDelay: 0.35,
  initialDelay: 0,
  spawnOffset: { x: 40, y: 66 },
} as const;

const dayPlants: PlantDef[] = [
  {
    id: 'peashooter',
    name: 'Peashooter',
    era: 'pvz1',
    introducedIn: 'pvz1-day-01',
    cost: 100,
    recharge: 7.5,
    health: 300,
    behaviors: [{ ...peaShot, projectile: 'pea' } satisfies ShooterSpec],
    tags: ['shooter', 'day'],
    description: 'Fires a pea at the first zombie in its lane, about every one and a half seconds.',
    audio: { fire: 'audio.throw' },
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    era: 'pvz1',
    introducedIn: 'pvz1-day-02',
    cost: 50,
    recharge: 7.5,
    health: 300,
    behaviors: [sunProduction],
    tags: ['producer', 'day'],
    description: 'Produces 25 sun roughly every 24 seconds. The first sun arrives 3 to 12.5 seconds after planting.',
  },
  {
    id: 'cherry-bomb',
    name: 'Cherry Bomb',
    era: 'pvz1',
    introducedIn: 'pvz1-day-03',
    cost: 150,
    recharge: 50,
    rechargeAtStart: 35,
    health: 300,
    behaviors: [{ type: 'explode', fuse: 1.2, damage: 1800, cols: 1, rows: 1, effect: 'cherry' } satisfies ExplodeSpec],
    tags: ['instant', 'day'],
    description: 'Explodes moments after planting, destroying every zombie in the 3 by 3 square around it.',
  },
  {
    id: 'wall-nut',
    name: 'Wall-nut',
    era: 'pvz1',
    introducedIn: 'pvz1-day-04',
    cost: 50,
    recharge: 30,
    rechargeAtStart: 20,
    health: 4000,
    behaviors: [],
    damageStages: [2 / 3, 1 / 3],
    tags: ['defensive', 'day'],
    description: 'A hard shell that holds zombies in place while they chew through 4000 health.',
  },
  {
    id: 'potato-mine',
    name: 'Potato Mine',
    era: 'pvz1',
    introducedIn: 'pvz1-day-06',
    cost: 25,
    recharge: 30,
    rechargeAtStart: 20,
    health: 300,
    behaviors: [{ type: 'mine', armTime: 15, damage: 1800, blast: 20 } satisfies MineSpec],
    tags: ['mine', 'day'],
    description: 'Takes 15 seconds to arm, then blows up the first zombie that touches it.',
  },
  {
    id: 'snow-pea',
    name: 'Snow Pea',
    era: 'pvz1',
    introducedIn: 'pvz1-day-07',
    cost: 175,
    recharge: 7.5,
    health: 300,
    behaviors: [{ ...peaShot, projectile: 'snow-pea' } satisfies ShooterSpec],
    tags: ['shooter', 'chill', 'day'],
    description: 'Fires frozen peas that hurt like normal peas and slow zombies to half speed for 10 seconds.',
    audio: { fire: 'audio.throw' },
  },
  {
    id: 'chomper',
    name: 'Chomper',
    era: 'pvz1',
    introducedIn: 'pvz1-day-08',
    cost: 150,
    recharge: 7.5,
    health: 300,
    behaviors: [{ type: 'chomper', reach: 60, biteDelay: 0.7, chewTime: 42, largeDamage: 40 } satisfies ChomperSpec],
    tags: ['melee', 'day'],
    description: 'Swallows the zombie in front of it whole, then spends 42 seconds chewing.',
  },
  {
    id: 'repeater',
    name: 'Repeater',
    era: 'pvz1',
    introducedIn: 'pvz1-day-09',
    cost: 200,
    recharge: 7.5,
    health: 300,
    behaviors: [{ ...peaShot, projectile: 'pea', burst: 2, burstGap: 0.15 } satisfies ShooterSpec],
    tags: ['shooter', 'day'],
    description: 'Fires two peas at a time.',
    audio: { fire: 'audio.throw' },
  },
];

const nightPlants: PlantDef[] = [
  {
    id: 'puff-shroom',
    name: 'Puff-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-01',
    cost: 0,
    recharge: 7.5,
    health: 300,
    nocturnal: true,
    behaviors: [{ ...sporeShot, range: 240 } satisfies ShooterSpec],
    tags: ['shooter', 'mushroom', 'night'],
    description: 'Free. Shoots spores at zombies up to three tiles away. Sleeps during the day.',
    audio: { fire: 'audio.puff' },
  },
  {
    id: 'sun-shroom',
    name: 'Sun-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-02',
    cost: 25,
    recharge: 7.5,
    health: 300,
    nocturnal: true,
    behaviors: [{ ...sunProduction, amount: 15, growAfter: 120, grownAmount: 25 } satisfies ProducerSpec],
    tags: ['producer', 'mushroom', 'night'],
    description: 'Makes 15 sun at a time, growing up after two minutes to make 25. Sleeps during the day.',
  },
  {
    id: 'fume-shroom',
    name: 'Fume-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-03',
    cost: 75,
    recharge: 7.5,
    health: 300,
    nocturnal: true,
    behaviors: [{ type: 'fume', damage: 20, interval: 1.5, intervalJitter: 0.15, fireDelay: 0.5, range: 320 } satisfies FumeSpec],
    tags: ['lane-attack', 'mushroom', 'night'],
    description: 'Fumes hit every zombie within four tiles and pass straight through screen doors. Sleeps during the day.',
    audio: { fire: 'audio.fume' },
  },
  {
    id: 'grave-buster',
    name: 'Grave Buster',
    era: 'pvz1',
    introducedIn: 'pvz1-night-04',
    cost: 75,
    recharge: 7.5,
    health: 300,
    nocturnal: true,
    placeOn: 'grave',
    behaviors: [{ type: 'grave-buster', time: 4.5 }],
    tags: ['mushroom', 'night'],
    description: 'Plant it on a grave to eat the grave. Sleeps during the day.',
  },
  {
    id: 'hypno-shroom',
    name: 'Hypno-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-05',
    cost: 75,
    recharge: 30,
    rechargeAtStart: 20,
    health: 300,
    nocturnal: true,
    behaviors: [{ type: 'hypnotize' }],
    tags: ['mushroom', 'night'],
    description: 'The zombie that bites it turns around and fights for you. Sleeps during the day.',
  },
  {
    id: 'scaredy-shroom',
    name: 'Scaredy-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-06',
    cost: 25,
    recharge: 7.5,
    health: 300,
    nocturnal: true,
    behaviors: [{ ...sporeShot, projectile: 'scaredy-spore', spawnOffset: { x: 44, y: 30 }, hideWithin: 80 } satisfies ShooterSpec],
    tags: ['shooter', 'mushroom', 'night'],
    description: 'Shoots spores the length of the lawn, but hides when a zombie comes near. Sleeps during the day.',
    audio: { fire: 'audio.puff' },
  },
  {
    id: 'ice-shroom',
    name: 'Ice-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-07',
    cost: 75,
    recharge: 50,
    rechargeAtStart: 35,
    health: 300,
    nocturnal: true,
    behaviors: [{ type: 'freeze-all', fuse: 1, damage: 20, freeze: 4, chill: 20 } satisfies FreezeAllSpec],
    tags: ['instant', 'mushroom', 'night'],
    description: 'Freezes every zombie on the lawn in place, then leaves them slowed. Sleeps during the day.',
  },
  {
    id: 'doom-shroom',
    name: 'Doom-shroom',
    era: 'pvz1',
    introducedIn: 'pvz1-night-08',
    cost: 125,
    recharge: 50,
    rechargeAtStart: 35,
    health: 300,
    nocturnal: true,
    behaviors: [
      { type: 'explode', fuse: 1, damage: 1800, cols: 3, rows: 2, effect: 'doom', crater: 180 } satisfies ExplodeSpec,
    ],
    tags: ['instant', 'mushroom', 'night'],
    description: 'A huge explosion that destroys zombies in a wide area and leaves a crater for three minutes. Sleeps during the day.',
  },
];

// Only ever handed out by the Wall-nut Bowling conveyor.
const bowlingPlants: PlantDef[] = [
  {
    id: 'wall-nut-bowling',
    name: 'Wall-nut',
    era: 'pvz1',
    introducedIn: 'pvz1-day-05',
    cost: 0,
    recharge: 0,
    health: 4000,
    behaviors: [{ type: 'bowl', speed: 250, damage: 1800, explode: false } satisfies BowlSpec],
    tags: ['minigame', 'bowling'],
    description: 'Rolls down the lane, bouncing between lanes after each hit.',
  },
  {
    id: 'explode-o-nut',
    name: 'Explode-o-nut',
    era: 'pvz1',
    introducedIn: 'pvz1-day-05',
    cost: 0,
    recharge: 0,
    health: 4000,
    behaviors: [{ type: 'bowl', speed: 250, damage: 1800, explode: true } satisfies BowlSpec],
    tags: ['minigame', 'bowling'],
    description: 'Rolls down the lane and explodes on the first zombie it hits.',
  },
];

export const pvz1Plants: PlantDef[] = [...dayPlants, ...nightPlants, ...bowlingPlants];
